name: Deploy

on:
  push:
    branches:
    - johannes/mdbook
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

env:
  MDBOOK_VERSION: v0.4.40
  MDBOOK_ADMONISH_VERSION: v1.18.0

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install mdbook
        run: |
          mkdir -p bin
          curl -sSL "https://github.com/rust-lang/mdBook/releases/download/$MDBOOK_VERSION/mdbook-$MDBOOK_VERSION-x86_64-unknown-linux-gnu.tar.gz" | tar -xz --directory=bin

      - name: Install mdbook-admonish
        run: |
          mkdir -p bin
          curl -sSL "https://github.com/tommilligan/mdbook-admonish/releases/download/$MDBOOK_ADMONISH_VERSION/mdbook-admonish-$MDBOOK_ADMONISH_VERSION-x86_64-unknown-linux-gnu.tar.gz" | tar -xz --directory=bin

      - name: Build
        run: |
          cd docs
          PATH=$PWD/../bin:$PATH mdbook build
          tree .

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/book/html

  deploy:
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
